(()=>{
const D=window.IELTS_LISTENING,S={part:0,answers:{},played:{},done:{},started:0,submitted:false,route:'intro'};let audio=null,tick=null;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function inject(){document.querySelectorAll('.topbar,.learn-top').forEach(nav=>{if(nav.querySelector('.listen-nav'))return;const b=document.createElement('button');b.className='listen-nav';b.innerHTML='<span class="listen-nav-dot"></span>Listening test';b.onclick=open;nav.appendChild(b)})}
function open(){S.route='intro';S.part=0;S.answers={};S.played={};S.done={};S.submitted=false;S.started=0;clearInterval(tick);render();if(location.hash!=='#listening-test')history.pushState(null,'','#listening-test')}
function start(){S.route='test';S.started=Date.now();render();}
function part(){return D.parts[S.part]}function flat(){return D.parts.flatMap(p=>p.q)}function answered(){return Object.keys(S.answers).length}
function home(){history.pushState(null,'','#bank');location.hash='bank';location.reload()}
function intro(){return `<main class="listen-shell"><nav class="listen-top"><button class="brand brand-button" data-home><span class="brand-mark">I/</span><span>IELTS TRAINING</span></button><span class="mono">LISTENING / PRACTICE TEST 01</span></nav><section class="listen-intro"><div><p class="eyebrow">LISTENING LAB / TEST 01</p><h1>Hear it once.<br><em>Understand it fully.</em></h1><p class="listen-lede">A 40-question IELTS-style Listening simulation with four parts, original recordings and no replay once a recording has started.</p><button class="button primary" data-start>Start listening test →</button></div><aside class="listen-card"><span class="mono">TEST FORMAT</span><strong>40</strong><span>questions</span><div><b>04</b><small>parts</small><b>1×</b><small>audio playback</small><b>A–C</b><small>multiple choice</small></div></aside></section><section class="listen-rules"><div><span>01</span><strong>Read before listening</strong><p>Questions follow the order of the recording. Read the options before you press play.</p></div><div><span>02</span><strong>No replay</strong><p>The recording controls are intentionally hidden. Once playback begins, you cannot restart that part.</p></div><div><span>03</span><strong>Review after</strong><p>Your answer key and score are revealed only after you submit the complete test.</p></div></section><p class="listen-disclaimer">Original educational content generated for this project. IELTS is a trademark of its respective owners and this site is not affiliated with IELTS.</p></main>`}
function test(){const P=part(),base=S.part*10,n=answered();return `<main class="listen-test"><header class="listen-header"><button class="icon-button" data-home aria-label="Back">←</button><div><span class="mono">LISTENING TEST 01</span><strong>Part ${P.number} · ${esc(P.title)}</strong></div><div class="listen-header-stats"><span data-clock>${fmt(S.started?Math.floor((Date.now()-S.started)/1000):0)}</span><span>${n}/40 answered</span></div><button class="button compact ${S.submitted?'secondary':'primary'}" data-submit>${S.submitted?'Results':'Submit test'}</button></header><div class="listen-progress"><span style="width:${n/40*100}%"></span></div><section class="listen-workspace"><aside class="listen-side"><div class="side-kicker">PART ${P.number}</div><h1>${esc(P.title)}</h1><p>${esc(P.context)}</p><div class="part-list">${D.parts.map((x,i)=>`<button class="part-tab ${i===S.part?'active':''} ${S.done[i]?'done':''}" data-part="${i}" ${i>S.part&&!S.done[i]?'disabled':''}><span>0${x.number}</span><div><b>Part ${x.number}</b><small>${esc(x.context)}</small></div><i>${S.done[i]?'✓':''}</i></button>`).join('')}</div></aside><article class="listen-main"><div class="audio-card"><div><span class="mono">RECORDING ${P.number}</span><strong>${S.played[S.part]?'Recording played':'Ready when you are'}</strong><p>${S.played[S.part]?'You can continue answering while the recording plays.':'Read the questions first, then start the recording. It will play once.'}</p></div><button class="play-once ${S.played[S.part]?'played':''}" data-play ${S.played[S.part]?'disabled':''}><span class="play-icon">${S.played[S.part]?'✓':'▶'}</span><span>${S.played[S.part]?'Played once':'Play recording'}</span></button><div class="audio-line"><span data-audio-progress></span></div></div><div class="question-head"><div><p class="eyebrow">${P.instructions.split('. ')[0]}</p><h2>Questions ${base+1}–${base+10}</h2></div><span class="mono">PART ${P.number} / 04</span></div><div class="listen-questions">${P.q.map((x,i)=>question(x,base+i)).join('')}</div><div class="listen-next"><button class="button secondary" data-prev ${S.part===0?'disabled':''}>← Previous part</button><button class="button primary" data-next ${!S.done[S.part]?'disabled':''}>${S.part===3?'Review answers':'Next part →'}</button></div></article></section></main>`}
function question(x,i){const a=S.answers[i];return `<section class="listen-question"><div class="listen-q-number">${String(i+1).padStart(2,'0')}</div><div class="listen-q-body"><h3>${esc(x[0])}</h3><div class="listen-options">${x[1].map((o,j)=>`<button class="listen-option ${a===j?'selected':''}" data-answer="${i}" data-choice="${j}"><span>${String.fromCharCode(65+j)}</span>${esc(o)}</button>`).join('')}</div></div></section>`}
function result(){const all=flat(),score=all.reduce((n,x,i)=>n+(S.answers[i]===x[2]?1:0),0),pct=Math.round(score/40*100);return `<main class="listen-result"><nav class="listen-top"><button class="brand brand-button" data-home><span class="brand-mark">I/</span><span>IELTS TRAINING</span></button><span class="mono">LISTENING / RESULT</span></nav><section class="listen-result-hero"><p class="eyebrow">PRACTICE COMPLETE</p><h1>${score}<span>/40</span></h1><p>${pct>=85?'Strong listening control. Review the misses and listen for the exact moment your interpretation changed.':pct>=70?'Good foundation. Your next gains will come from recognising paraphrase and distractors faster.':'Use the result diagnostically. Review each miss and identify whether the problem was prediction, attention, vocabulary or interpretation.'}</p><div class="result-actions"><button class="button primary" data-review>Review answers →</button><button class="button secondary" data-retry>Retake test</button></div></section><section class="listen-breakdown"><div><span>ACCURACY</span><strong>${pct}%</strong></div><div><span>CORRECT</span><strong>${score}</strong></div><div><span>MISSED</span><strong>${40-score}</strong></div><div><span>TIME</span><strong>${fmt(S.started?Math.floor((Date.now()-S.started)/1000):0)}</strong></div></section><section class="listen-answer-sheet"><div class="section-head compact-head"><div><p class="eyebrow">ANSWER KEY</p><h2>Forty listening decisions.</h2></div><button class="button-link text-link" data-home>Back to training →</button></div>${all.map((x,i)=>{const a=S.answers[i],ok=a===x[2];return `<button class="listen-answer-row ${ok?'ok':'miss'}" data-review-q="${i}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x[0])}</span><em>${a===undefined?'—':String.fromCharCode(65+a)}</em><small>${ok?'Correct':`Correct: ${String.fromCharCode(65+x[2])}`}</small></button>`}).join('')}</section></main>`}
function tick(){clearInterval(tick);tick=setInterval(()=>{$('[data-clock]')?.replaceChildren(fmt(Math.floor((Date.now()-S.started)/1000)))},1000)}
async function play(){if(S.played[S.part])return;const P=part(),b=$('[data-play]');b.disabled=true;b.classList.add('loading');b.querySelector('span:last-child').textContent='Loading recording…';audio=new Audio(P.audioUrl);audio.preload='auto';S.played[S.part]=true;audio.ontimeupdate=()=>{const p=audio.duration?audio.currentTime/audio.duration*100:0;$('[data-audio-progress]')?.style.setProperty('width',p+'%')};audio.onended=()=>{S.done[S.part]=true;render()};audio.onerror=()=>{S.played[S.part]=false;audio=null;render();alert('The pre-generated recording could not be loaded. Generate the static audio assets from the repository workflow, then refresh.')};try{await audio.play();render();tick()}catch(e){S.played[S.part]=false;audio=null;render();alert('Could not start the recording. Please tap Play again.')}}
function submit(){S.submitted=true;clearInterval(tick);if(audio){audio.pause();audio=null}S.route='result';render()}
function render(){clearInterval(tick);document.querySelector('#app').innerHTML=S.route==='intro'?intro():S.route==='test'?test():result();bind();if(S.route==='test')tick();window.scrollTo({top:0,behavior:'instant'})}
function bind(){$$('[data-home]').forEach(b=>b.onclick=home);$('[data-start]')?.addEventListener('click',start);$('[data-play]')?.addEventListener('click',play);$$('[data-answer]').forEach(b=>b.onclick=()=>{if(S.submitted)return;S.answers[+b.dataset.answer]=+b.dataset.choice;render()});$$('[data-part]').forEach(b=>b.onclick=()=>{S.part=+b.dataset.part;render()});$('[data-prev]')?.addEventListener('click',()=>{S.part=Math.max(0,S.part-1);render()});$('[data-next]')?.addEventListener('click',()=>{if(S.part<3){S.part++;render()}else submit()});$('[data-submit]')?.addEventListener('click',()=>{if(confirm('Submit the complete listening test and reveal the answer key?'))submit()});$('[data-review]')?.addEventListener('click',()=>{S.route='test';S.submitted=true;S.part=0;render()});$('[data-retry]')?.addEventListener('click',()=>open());$$('[data-review-q]').forEach(b=>b.onclick=()=>{S.route='test';S.submitted=true;S.part=Math.floor(+b.dataset.reviewQ/10);render()})}
const obs=new MutationObserver(inject);obs.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{const trigger=e.target.closest?.('[data-listening]');if(trigger){e.preventDefault();e.stopPropagation();open()}});
window.addEventListener('hashchange',()=>{if(location.hash==='#listening-test')open();});
window.IELTS_OPEN_LISTENING=open;
if(location.hash==='#listening-test')open();else inject();
})();